name: Deploy site files in master env

on:
  push:
    branches:
      - master # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: npm build
        run: |
          yarn
          yarn run build

      - name: Deploy org
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:Ark-survey/product-env.git
          BRANCH: main
          FOLDER: build
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}

      - name: Deploy per
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: git@github.com:HEGGRIA/Ark-survey-product-env.git
          BRANCH: main
          FOLDER: dist
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
